language: go

go:
  - 1.6
  - 1.5
  - tip

before_install:
  - curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -

before_script:
  - go get -u github.com/golang/lint/golint

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./)
  - diff -u <(echo -n) <(golint ./)
  - go test -v -race -covermode=atomic -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci
